### ISSUE TITLE
change language again

### ISSUE THREAD

**Issue by treakiandroid** [charbgr/Anagram-Solver#4]
hi, as ive started the app it has asked in which language i want to search anagrams and i chosen german. now i want to try it in english but i cant find a way to go back to the language choose screen. i can't see anything else then the search and result boxes. i would expect some about this app screen and some settings screen..

am i missing this option somehow or dose it not exist, if so add it please otherwise plz tell me how to change language.

thanks

**Comment by charbgr** [comment]
@treakiandroid  Yes, actually this is something I want to implement in the future but I didn't find some time! 
If you want you can make a pull request!
