### ISSUE TITLE
enable IME dictionary

### ISSUE THREAD

**Issue by treakiandroid** [charbgr/Anagram-Solver#5]
if i am typing in text here on my phone i get suggestions while i type from the android keyboard. The anagram solver input field property's doese seem like that has been disabled. i would suggest enabling that by default and maybe add a setting option for that.

thanks

**Comment by charbgr** [comment]
@treakiandroid I don't think that this will be implemented. Actually the search box is over there for anagrammized terms. Suggestions are not anagrammized words. Why do you want them?
